### ISSUE TITLE
Group 98 to be double checked

### ISSUE THREAD

**Issue by dede2021** [SuLab/DrugMechDB#303]
This should be checked by @TanskaAnnna.

If all is well, I can open a PR, which will automatically feed into the DrugMechDB website.

Group 98 curation can be found here:
https://github.com/dede2021/DrugMechDB/blob/main/submission.yaml

**Comment by TanskaAnnna** [comment]
@dede2021 this issue is just for test purposes right? I've pushed your PR for group 93 yesterday (https://github.com/SuLab/DrugMechDB/pull/279), so I'm a lilttle bit confused now. Only the deletion of your 2 paths from that group did not work and this issue with deletions hopefully will be sorted out soon.

**Comment by dede2021** [comment]
My bad @TanskaAnnna. Title should be Group 98, not Group 93.

**Comment by dede2021** [comment]
Duplicated.

Comms should be made in previous issue [#274](https://github.com/SuLab/DrugMechDB/issues/274).
